####################################################
# LSrouter.py
# Name:
# HUID:
#####################################################
import json
import heapq
from router import Router
from packet import Packet


class LSrouter(Router):
    """Link state routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        self.neighbors = {}  # port -> (endpoint, cost)
        self.tropology = {}  # addr -> (seq_num, neighbors)
        self.forwarding_table = {}  # dst_addr -> (next_hop, cost)
        self.seq_num = 0
    
    def flood_lsp(self, expect_port = None):
        self.seq_num += 1
        neighbors_dict = {}
        for port in self.neighbors:
            neighbor, cost = self.neighbors[port]
            neighbors_dict[neighbor] = cost
        self.tropology[self.addr] = {
            "seq" : self.seq_num,
            "neighbors" : neighbors_dict
        }
        msg = {
            "src" : self.addr,
            "seq" : self.seq_num,
            "neighbors" : neighbors_dict
        }
        pkt = Packet(
            Packet.ROUTING,
            self.addr,
            None,
            json.dumps(msg)
        )
        for port in self.neighbors:
            if port != expect_port:
                self.send(port, pkt)
    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            pass
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the sequence number is higher and the received link state is different
            #   update the local copy of the link state
            #   update the forwarding table
            #   broadcast the packet to other neighbors
            pass

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        pass

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        pass

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the link state of this router to all neighbors
            pass

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"LSrouter(addr={self.addr})"
